n = int(input())
m = int(input())
arr1 = list(map(int, input().strip().split()))
arr2 = list(map(int, input().strip().split()))
a1 = abs(min(arr1))
a2 = abs(max(arr1))
b1 = abs(min(arr2))
b2 = abs(max(arr2))
print(max(a1*b1, a1*b2, a2*b1, a2*b2))
